### ISSUE TITLE
DlToast > add collapse ability

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#103]
We would like to have after N toasts to collapse and delete the old one and keep new ones

Lets say this is a prop called collapse-count with default of null ( no collapsing ) 
when passing a number to this prop 

it will after collapse-count of toasts delete oldest and add a new one

**Comment by ORily287** [comment]
please merge it to the open PR #107 @denfedweb

**Comment by denfedweb** [comment]
> please merge it to the open PR #107 @denfedweb

merged
