### ISSUE TITLE
DlSelect - DlMenu position doesn't get updated on scroll

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#117]
When opening the dl-select and scrolling outside of it, the menu's position doesn't get updated.
This happens not only here, but in every component that uses portal (for example, dl-tooltip).
![image](https://user-images.githubusercontent.com/120374103/229562942-e168c4d7-b75b-4c65-9e06-d033568d4851.png)

**Comment by SorinOpt** [comment]
@advaa1234 we cannot reproduce this issue on the current repo

**Comment by fadiDL** [comment]
@advaa1234 @SorinOpt Please check this in OA with components demo
I believe its related to Vue2 issues maybe
