### ISSUE TITLE
[BUG] DlSmartSearch - component does not emit correct filter on search

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#122]
**Describe the bug**
Currently we are trying to implement and use the smart search component
i took the demo page and tried to perform basic tasks on it like write a filter and click search

**To Reproduce**
1. Go to DlSmartSearchDemo 
2. Write a search
3. Click the search icon

**Expected behavior**
A translated to json query of the text to be sent as the active query back instead of activequery being null.

Also ! we have this issue with active filters and quries 
![image](https://user-images.githubusercontent.com/99925584/229793528-bdcbf075-7c95-4bf8-a9ec-34db68189152.png)

**Comment by prodan-eric** [comment]
I changed the label to enhancement because back when we built this we didn't receive a formula for parsing a string query to JSON. This being a more complex task, could you tell us how a particular query string ( say: Name = 'John' AND Age = 22) would look in JSON form?

**Comment by fadiDL** [comment]
Sure thing @prodan-eric 

we can use basic mongo filters to define such behaviors 

A = 5 and B = 6 => { $and: [ { A: 5} , { B: 6 } ] } 

Same thing for OR statement 

For the example given `Name = 'John' AND Age = 22`
then 
```js
{
  $and: [{ name: "John" }, { age: 22 }];
}
```

Furthermore this is how OR statements would work 

 For the example given `Name = 'John' OR 'Fadi' AND Age = 22 OR 5` 
** excuse me if the syntax of OR is incorrect here but its a general explanation 
then 
```js
{
  $and: [
    { $or: [{ name: "John" }, { name: "Fadi" }] },
    { $or: [{ age: 22 }, { age: 5 }] },
  ];
}
```
