### ISSUE TITLE
[BUG] DlTable using external DlPagination - Pagination prop isn't reactive

### ISSUE THREAD

**Issue by Yonatan-Mesika** [dataloop-ai/components#123]
**Describe the bug**
When using the DlTable component with an external DlPagination component, when I update the pagination object via the DlPagination - the table isn't reactive to this change.
Currently, I'm using the following workaround to achieve the required update - 
![image](https://user-images.githubusercontent.com/112543467/229793208-931e788d-1fc9-4449-b9c8-34a5a15b4e77.png)

**To Reproduce**
1. Create a DlTable component with the `hide-bottom` prop and pass a Pagination object.
2. Create a DlPagination component to manage the Pagination object. 
3. Move to the next page and update the Pagination object.
4. The DlTable rows won't be changed. 
 
**Expected behavior**
The DlTable rows should be updated as per the page in the Pagination object.

**Comment by SorinOpt** [comment]
@Yonatan-Mesika fixed on https://github.com/dataloop-ai/components/pull/131
