### ISSUE TITLE
[BUG] DlTable > hasClickEvents doesnt work

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#127]
The use of checking if we have event props and such is incorrect this should be checked in events.
please change the check to if there is any event registered 

i removed the restriction on emitting events in general
thats only needed for visual pointer

check this pr 
https://github.com/dataloop-ai/components/pull/128/files

**Comment by SorinOpt** [comment]
@fadiDL I checked the PR, and there is no need for event checks. I agree, but it's unclear which changes I should make now. Can you provide more details, please?
