### ISSUE TITLE
[FEATURE] DlTabs - need for "top-right" slot

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#150]
**Is your feature request related to a problem? Please describe.**
In the old `DlTabs` there is `a top-right" slot, which I believe is the same as in the `dl-table`, and I got a Figma design that uses the `top-right` slot. 

**Describe the solution you'd like**
Add `top-right` slot as @rotemshaham or Bar describe it 

**Describe alternatives you've considered**
for now, I use the old `Dl-Tabs` but it did not exactly fit other design 

** screenshots ** 
from the Figma design of the `new-service-page`
![image](https://user-images.githubusercontent.com/127755482/231727301-7c039383-72d3-463b-b6ff-7d17f7f7d916.png)

**Comment by ORily287** [comment]
@fadiDL @rotemshaham please add your input to this feature request

**Comment by Barp311** [comment]
https://github.com/dataloop-ai/components/pull/186 
already replied see the link  ^^^
