### ISSUE TITLE
[CRITICAL] DlCalendar - flaky tests

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#158]
we introduced already a fix to this test and it keeps breaking again 
![image](https://user-images.githubusercontent.com/99925584/232293416-ea0c6b1f-91ac-4cfc-af02-d1093916ae31.png)
https://github.com/dataloop-ai/components/pull/149

This is top priority and it seems that this test needs to be rewritten or have better handling for it in case of reactivity

**Comment by SorinOpt** [comment]
@fadiDL This issue cannot be reproduced on the `main` branch
