### ISSUE TITLE
[FEATURE] DlTextArea - is missing props `error` and `errorMessage`

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#159]
**Describe the bug**
DlTextArea is not implemented props `error` and `errorMessage` in the code. 

**To Reproduce**
1. Go to [DlTextArea](https://dataloop-ai.github.io/components/?path=/docs/library-components-dltextarea--docs)
2. See that there is no props `error` and `errorMessage`

1. Go to [dlTextArea.vue](https://bitbucket.org/dataloop-ai/dl-components/src/315db78fed1a0281f80b72dc915355616a805d09/src/components/DlTextArea.vue#lines-35:64)
2. see that the above props are not defined

**Expected behavior**
props `error` and `errorMessage` should be defined as in all `dl-input` components

**Comment by fadiDL** [comment]
@perydataloop This is not a bug. this is a feature request.
the behavior was not requested / designed for the dl-text-area component.

Changing the status to enhancement
