### ISSUE TITLE
DlChip - removable X shows up on the text itself

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#18]
**Describe the bug**
When using the removable prop & a label slot, the X shows up on the text.
When using a label slot, the "remove" emits an empty string.

**Screenshots**
Without removable:
![image](https://user-images.githubusercontent.com/120374103/223178540-c3aa86e7-4173-41f3-b821-45e9b9b8a0fa.png)
With removable:
![image](https://user-images.githubusercontent.com/120374103/223179493-b03f1c08-a97a-4bdd-bc45-58eb77aeafd0.png)

**Comment by SorinOpt** [comment]
@advaa1234 I cannot reproduce this bug on the current repository, it appears on implementation on other projects or here?
