### ISSUE TITLE
Dl checkbox - issues

### ISSUE THREAD

**Issue by Barp311** [dataloop-ai/components#216]
1. **Describe the bug**
space between checkbox icon and text is 5px
![image](https://user-images.githubusercontent.com/131682129/236208170-584672e5-61e2-4cc4-bd0b-962088ae1171.png)

**Expected behavior**
change space to 10 px

<img width="686" alt="image" src="https://user-images.githubusercontent.com/131682129/236209051-d638546e-a7d4-459f-b05c-f2046c602c84.png">

2. **Describe the bug**
sub text is not align to the title. 

![image](https://user-images.githubusercontent.com/131682129/236208604-3a8d8022-182b-4102-8ad9-d50f4f3edaae.png)

**Expected behavior**
align sub text left - to the title. 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/131682129/236209090-58b3a199-77d9-401f-9770-c9edcd347a2c.png">

**Comment by denfedweb** [comment]
1 - space between checkbox icon and text is 10px, what is shown in the screenshot is the distance around
