### ISSUE TITLE
DlChip - issues01

### ISSUE THREAD

**Issue by Barp311** [dataloop-ai/components#221]
**Describe the bug**
1. padding
<img width="369" alt="image" src="https://user-images.githubusercontent.com/131682129/236252746-ec78ed4a-3baa-40db-bb2d-609c7b95ba9c.png">

**Expected behavior**

<img width="420" alt="image" src="https://user-images.githubusercontent.com/131682129/236254416-343b4142-e37d-47ec-bb60-0acb60a7ba17.png">

--------
2. **Describe the bug**
a. add an option to remove the  text - only icon remain.
b. add an option to remove the icon - only text remain.

**Comment by denfedweb** [comment]
2 - is possible
