### ISSUE TITLE
[BUG] DLDropDownButton - style issue

### ISSUE THREAD

**Issue by Barp311** [dataloop-ai/components#227]
1. **Describe the bug**

The length of the text: IF the text length is More than container width display with 3 dots and add a tooltip with the entire name on hover (no text wrapping).

![image](https://user-images.githubusercontent.com/131682129/236763159-d7606d11-3c7c-4da8-8119-835c78cb1836.png)
![image](https://user-images.githubusercontent.com/131682129/236763488-6bd5e5cc-b279-46a7-8351-e19d4d86ef70.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/131682129/236763445-bc40eb2f-12df-45a2-8b86-299cda74f9c0.png)

---------------

2.**Describe the bug**
structure issues:
![image](https://user-images.githubusercontent.com/131682129/236763717-77821cf0-70a8-4f4f-919a-ea8531e31138.png)

**Expected behavior**
https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=2179-11692&t=GRtVgVdAwIK5fld2-0

**Comment by SorinOpt** [comment]
1. see the dropdown demo page using the ellipsis component.
2. fixed
