### ISSUE TITLE
[FEATURE] DL Widget - issues

### ISSUE THREAD

**Issue by Barp311** [dataloop-ai/components#241]
see more: [dl widget figma](https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=10228%3A151218&t=Ans7vSgDDcMDNBd2-1)

1. widget need to be aligned

![Screenshot 2023-05-09 at 9 44 39](https://user-images.githubusercontent.com/131682129/237015798-2d6e2b0f-885b-410c-9866-e3a6f496bd29.png)

2. The widgets needs to be responsive to the screen size
3. There is a problem with scrolling with the widget. There are times when it doesn't scroll at all, and there are times when it jumps
4. tThere is no indication for drug and drop - it should display as follows:

- display on hover the chart the drag button.
- on hover diaply the mouse cursor mouse cursor: grab        and grabing
- drop shadow: var (--dl-color-shadow) light theme: #101E73 15% (x-0 y-3 b-6 spread-0)  dark theme: #292e35 50% (x-0 y-3 b-6 spread-0)
- background color (while dropping the row to his new place): var(--dl-color-fill)

5. text color should be: var (--dl-color-medium) 
![image](https://user-images.githubusercontent.com/131682129/237018390-1fd76c84-110b-4399-ab3b-bd15a6bceb9c.png)

6. padding need to be 16px
<img width="559" alt="image" src="https://user-images.githubusercontent.com/131682129/237019176-9fb004f2-b7fe-4f4b-9100-ad0e27ad3244.png">

how it displayed in the story book: 
![image](https://user-images.githubusercontent.com/131682129/237019280-e52bd0a8-65d0-410b-800a-ad12c82af546.png)

![image](https://user-images.githubusercontent.com/131682129/237019333-f55c42da-d198-4939-9f73-80b65168d0ba.png)

7. where can i see icons buttons + menu?

**Comment by prodan-eric** [comment]
1. Should be aligned
![image](https://github.com/dataloop-ai/components/assets/115978006/756177d6-20d3-468c-8656-f267bc3dd65b)

2. Checked again, should be responsive
![dl-grid-responsive](https://github.com/dataloop-ai/components/assets/115978006/e1c82f0a-00fc-4da6-a15a-68e008c23241)

3. You mean the scrolling on the Bar Chart ?  I tried reproducing this bug and didn't encounter any issues, maybe send me a gif/video

4. Fixed it, should be good now
![grid-grab](https://github.com/dataloop-ai/components/assets/115978006/eb99e24f-cd87-4fba-bab9-c1794afa0658)

5. Any header/footer text or content inside the widget is managed from outside, so you can pass anything you want of any color you want. I made the  demo text be dl-color-medium though: 
![image](https://github.com/dataloop-ai/components/assets/115978006/0d350295-5951-48c3-bf8d-5c851c8051ab)

6. Added a padding of 15px to each widget, this gets added to the row and column gap too, so there might be too much space, check it and let me know if it's ok
![Screenshot from 2023-05-12 16-54-03](https://github.com/dataloop-ai/components/assets/115978006/09d5f047-70df-443d-8525-1a42bea7e39f)

7. The menu options are also passed from outside as a slot, I added two icon buttons on the first demo widget:
![image](https://github.com/dataloop-ai/components/assets/115978006/fdd311da-f7b5-4109-b76d-4890be2250af)
