### ISSUE TITLE
[BUG] dl typography - not editable

### ISSUE THREAD

**Issue by Barp311** [dataloop-ai/components#252]
dl typography is not editable - 
typography figma:
https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=1040-3614&t=v1mE5fEMW845MdO0-0

**Comment by rotemshaham** [comment]
@VictorOpenTech I don't know what she meant...
@ORily287 we can close this ticket.

**Comment by VictorOpenTech** [comment]
@rotemshaham, great you have access to GitHub. A week ago I haven't understood what was expecting from us.
If Bar have in mind to edit the colour, uppercase or size - it's possible to do it directly from StoryBook, the variant is editable as well. Maybe she meant the design of Typography changed or we should polish-up the Typography when we switched for the actual version of StoryBook, or even to have possibility to edit the sizes from the fonts or variants directly from StoryBook. @ORily287 we could keep it in our Backlog and latter on we'll have a closer look. I've change the priority as 'low' so we'll not forget about it latter on

**Comment by rotemshaham** [comment]
@VictorOpenTech we already discussed this ticket. It's a mistake. There is no work to be done here. @ORily287 please close the ticket.
