### ISSUE TITLE
Smart Search - issues #4

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#267]
1. When choosing a filter it will automatically change the query
- it should only change the query when you click query
- when writing a query in new query and then changing to a saved one it deletes the new query. (maybe we should keep it for now and clear the state when dialog isclosed)

2. dql filter editor
![image](https://github.com/dataloop-ai/components/assets/99925584/e3c39119-4111-46e9-86f6-519e0af42571)
when trying to type new empty filter it will show suggestion on the smart input and it automatically keeps validating (ti should validate only after x amount of debouncing)

3. json editor 
break out the json editor component without the filter selector and others just keep the editor itself without the dialog so we can use in other components

4. translation to string from mongo does not go over the generated text and replace the aliases back to aliases.

**Comment by prodan-eric** [comment]
1. From what I understood selecting queries inside the json editor should not reflect in the search bar unless the user clicks on the Search button. I made that change. Also, I made it so writing a new query will keep it saved and remember it even if the user selects other queries and then comes back to the new query.
2. I'm not sure how to change this error delay inside the json-editor object. I looked it up in their library docs but didn't find anything.
3. I moved the dialog box wrapper outside the DlJsonEditor component, leaving only the editor itself and the dl-select inside.
4. I made it so translating back to the string version of the query also replaces original keys with aliases
