### ISSUE TITLE
DlTable - pagination issue

### ISSUE THREAD

**Issue by Yonatan-Mesika** [dataloop-ai/components#28]
**Describe the bug**
When trying to edit the `rowsPerPageOptions` prop (which is related to DlPagination) - nothing is happen! (validated in the Storybook & OpenAnnotation).
Also, we don't have the ability to adjust the DlPagination via the DlTable params - I don't know if this is by design. but if not we should find a proper way to allow that. 

**To Reproduce**
1. Go to Storybook/OpenAnnoitation.
2. Adjust the `rowsPerPageOptions` prop with any valid values

**Actual behavior**
The options in **Rows per page** selection is always [10,15,20,25,50,100], without related to the values we passed.

**Expected behavior**
The options in **Rows per page** selection should include the values we passed in the `rowsPerPageOptions` prop.

**Screenshots**
![image](https://user-images.githubusercontent.com/112543467/223713626-3d2d811b-2e73-4d0c-b41c-84a143305f66.png)

**Device (please complete the following information):**
 - OS: PopOs
 - Browser: Chrome
 - Version: latest.

**Comment by perydataloop** [comment]
Is also appears in the real code. tweaking  the `rowsPerPageOptions`  does not do any notice
