### ISSUE TITLE
[BUG]  DlStepper - Stepper class issue

### ISSUE THREAD

**Issue by dlZmiro** [dataloop-ai/components#282]
Hello,

I have identified a bug in the Stepper class that is used by the dlStepper component. The issue occurs when there are fast transitions between steps and rapid updates to the current step(stepper.currentStep). This bug affects the functionality of the dlStepper component.

**To Reproduce**
1- Include the dlStepper component in your application, utilizing the Stepper class.
2- Create a scenario with fast transitions between steps.
3- Rapidly update the current step during the transitions with errors or warnings.
4- Observe the unexpected behavior, errors or warnings that occur.

**Expected behavior**
When utilizing the Stepper class within the dlStepper component, the component should handle fast transitions between steps and rapid updates to the current step gracefully, without errors or unexpected behavior.

**Device:**
 - OS: macOS
 - Browser: Chrome
 - Version : Version 113.0.5672.126

**Comment by fadiDL** [comment]
Added few handling for you to set different behavior with the stepper class operations
