### ISSUE TITLE
DlEllipsis - Console error & component not working as expected

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#305]
When trying to use DlEllipsis, it doesn't create the wanted result on the first render.
![image](https://github.com/dataloop-ai/components/assets/120374103/3c04a184-2b29-4664-9079-f90fc42704e8)

Also getting these errors on the demo:
![image](https://github.com/dataloop-ai/components/assets/120374103/4823fc03-8159-46fe-9ec2-1b891eecf8c5)

**Comment by SorinOpt** [comment]
<img width="648" alt="Screenshot 2023-05-24 at 12 54 08" src="https://github.com/dataloop-ai/components/assets/127127362/b7e19eeb-c623-4caa-ae1c-72db46d14f5f">
