### ISSUE TITLE
[BUG] dl-select - select menu is not open by clicking on arrow up or down

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#309]
**Describe the bug**
dl-select has support now for the keyboard, it got focus, arrows keys up or down  in the ,opened menu,  can use to navigate trow the options. but all of that is worth nothing if the user still needs the mouse to open the `dl-select`s menu . 

**Expected behavior**
- after the user focuses on `dl-select` push  arrow down will open the `dl-menu` with option 0 selected. 
- arrow up from menu position 0, will focus back dl-select and maybe close the menu

**Comment by prodan-eric** [comment]
@perydataloop  The select can be opened by pressing enter (instead arrow down) when it's selected.
