### ISSUE TITLE
[FEATURE] {{ dl-text area }} - {{ Attach image }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#324]
Figma spec: [https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=15843%3A222866&t=MzfcQ3Ycf3Ue9LBM-1](url)

The addition allows users to attach images while writing a comment inside the text input area.

**Comment by fadiDL** [comment]
This will be handled in a new redesign with #340
