### ISSUE TITLE
[BUG] DlTable - virtual scroll issues

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#326]
1. when having virtual scroll the scroll is shown also on the first row which is sticky
![image](https://github.com/dataloop-ai/components/assets/99925584/8e2a80cf-5e42-41da-a4ea-fbd4f1edd4c4)

2. we have to pass 
`:pagination="{ rowsPerPage: 0 }"`
with virtual-scroll if we want it to work properly.

i expect to not need to pass this basic requirement to the virtual scroll component.

3. we have send height styling to the table even tho its already limited by its parent to have a functional virtual scroll

4. Table implementation just to add virtual scrollshould be 
```
    <dl-table
        :columns="columns"
        :rows="orgMembers"
        hide-pagination
        hide-bottom
        row-key="name"
        virtual-scroll
    >
   ```
 
 and we should also make sure that vritual scroll is also as clean as this implementation
 
 5. we have weird behavior when there are lot of components in the virtual scroll list it will sometimes bug and lag and jump with the scrolling. the scroll then would jump backwards so youd have to scroll more to get to the point that you want.

**Comment by SorinOpt** [comment]
2. Notice that when enabling ```virtual scroll``` you will need to specify the ```table-style``` (with a max-height) prop. In the example below, we are also forcing DlTable to display all rows at once (note the use of ```pagination``` and ```rows-per-page-options props```).
