### ISSUE TITLE
[BUG] {{ dl-input & dl-text area }} - {{ icon button issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#329]
1. The icon should be a button with all its states + a tooltip on hover. 
2. The icon should be placed in the center of the input. In the dl text area, it should be at the top-right. 
3. A prop for the icon button size is missing. 
4. Text input in size S:  The icon does not appear. 
5. Text input size XL: The button is not in the right place
6. The location of the cancel button is not by design. 
7. In dl text area- the button is missing. 
![Screenshot 2023-05-24 at 15 53 03](https://github.com/dataloop-ai/components/assets/121247551/f9c6774a-7ae1-4c8e-843f-ee95b9fae926)
![Screenshot 2023-05-24 at 15 52 52](https://github.com/dataloop-ai/components/assets/121247551/1524a814-6777-4907-8f85-a808e3d3a930)
![Screenshot 2023-05-24 at 15 52 47](https://github.com/dataloop-ai/components/assets/121247551/6467bbd9-7e9a-48f0-80ce-a9157fb29807)

Please open the spec again and ensure we align with the requirements.

**Comment by fadiDL** [comment]
This should be handled as part of a redesign #340
