### ISSUE TITLE
[FEATURE] {{ dl-date range }} - {{ new additions }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#350]
Figma: [https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=16061%3A224153&t=waTmbKFBbBWEKEpx-1](url)
1. Set option to null date- the placeholder will be: Set due date
2. Add a clear date button to return to the initial state. 
3. reduce the paddings top, bottom, left & right (From 30 to 16px) 
![Screenshot 2023-05-31 at 16 10 31](https://github.com/dataloop-ai/components/assets/121247551/7dc9b585-e3f2-4460-a801-346bff781a95)
![Screenshot 2023-05-31 at 16 10 26](https://github.com/dataloop-ai/components/assets/121247551/a6d6b57d-b678-4432-8f0f-6277b3c23400)

**Comment by perydataloop** [comment]
Ccurious, Where should the clear button appear? I can't see it the attached images

**Comment by rotemshaham** [comment]
@perydataloop @VictorOpenTech The design is in the attached link.
