### ISSUE TITLE
[BUG] {{ dl-widget }} - {{ UI issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#372]
1. title color and size: color: dl-color-darker, size: 20px
![Screenshot 2023-06-01 at 14 23 12](https://github.com/dataloop-ai/components/assets/121247551/3727073e-9fa4-4f59-9585-1d326a050f83)

2. subtitle color: dl-color-medium
![Screenshot 2023-06-01 at 14 23 31](https://github.com/dataloop-ai/components/assets/121247551/c8be2ec1-8f0e-49ac-bd80-a97c8da254d2)

3. drag button should be aligned to the center of the header. The button should be located at the top of the header. 
![Screenshot 2023-06-01 at 14 25 11](https://github.com/dataloop-ai/components/assets/121247551/d7c6ab54-d508-488d-8f6f-d61436f83826)

4. Buttons size should be 16px. 
![Screenshot 2023-06-01 at 14 29 49](https://github.com/dataloop-ai/components/assets/121247551/90f334f8-c875-41a7-bd9e-fa14bf99e745)

5. The scroll bar looks tiny. 
![Screenshot 2023-06-01 at 14 31 20](https://github.com/dataloop-ai/components/assets/121247551/da387818-e1d4-492d-b1ee-8ed93033a514)
![Screenshot 2023-06-01 at 14 31 28](https://github.com/dataloop-ai/components/assets/121247551/bbcd0414-ac54-4783-ba20-05db48966490)

Figma: 
![Screenshot 2023-06-01 at 14 26 26](https://github.com/dataloop-ai/components/assets/121247551/399ad1f0-d15b-43ed-ac7f-d7de4b90dc38)

**Comment by prodan-eric** [comment]
1,2,4: Title, subtitle, and menu buttons are fully customizable from outside (slots) but I updated the demo too.
4: Fixed the drag icon at the top of the widget.
5: The scroll bar thickness adjusts according to the chart size but I added a minimum width of 5px. That fixes it getting too small.
