### ISSUE TITLE
[BUG] {{ dl toast }} - {{ UI issue }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#373]
1. The shape of the counter should be a circle. 
![Screenshot 2023-06-01 at 14 34 00](https://github.com/dataloop-ai/components/assets/121247551/13e00a22-5b69-4e9a-9cc8-798209c8a53e)

**Comment by fadiDL** [comment]
works fine 
<img width="250" alt="image" src="https://github.com/dataloop-ai/components/assets/99925584/881fc9c1-139e-4b74-a7f0-71e4466f2511">

<img width="88" alt="image" src="https://github.com/dataloop-ai/components/assets/99925584/2fdc5060-2a78-4a27-b42b-efdf74e9cf6b">

closing issue
