### ISSUE TITLE
[BUG] {{ dl doughnut chart }} - {{ UI issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#375]
1. This tooltip looks different from the other tooltips.
![Screenshot 2023-06-01 at 14 56 43](https://github.com/dataloop-ai/components/assets/121247551/01e25553-6286-4e8f-8db4-72a4146450e4)
ifferent from the other tooltips:

![Screenshot 2023-06-01 at 14 56 20](https://github.com/dataloop-ai/components/assets/121247551/b39d43c1-5156-4a9a-900f-13b21726a5bd)
f54813)

2. The tooltip's position seems quite distant from the corresponding legend label.
![Screenshot 2023-06-01 at 14 57 14](https://github.com/dataloop-ai/components/assets/121247551/af264061-3d61-40de-8032-97db3e0a768c)

3. the color inside the tooltip looks different from the color in
![Screenshot 2023-06-01 at 15 01 58](https://github.com/dataloop-ai/components/assets/121247551/c2e1d4c1-e88b-454e-b206-ed445d39a45b)
 the ring.

**Comment by vadim-popa-opentech** [comment]
The tooltip now is the same for all segments. The tooltip LabelColor has fixed

![image](https://github.com/dataloop-ai/components/assets/127128115/ceb9fe3e-3973-49a1-911f-7e30a1326481)

![image](https://github.com/dataloop-ai/components/assets/127128115/1e69e3d1-42d5-4264-9489-7fb668710e6b)

For legends. The tooltip appears if the label has ellipsis

![image](https://github.com/dataloop-ai/components/assets/127128115/513d1902-a7b6-4a65-922a-b6ac72834dbe)

![image](https://github.com/dataloop-ai/components/assets/127128115/f6eb753c-d01f-4cd8-91c1-977bd3e7a891)
