### ISSUE TITLE
[BUG] {{ dlconfusion matrix }} - {{ UI issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#384]
1. Figma: https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=11762%3A172419&t=BwWcmWzggkKLUmgf-1
2. The values (the numbers) are too small (7.2px???). Change the minimum font size to 12px. 
![Screenshot 2023-06-05 at 10 48 53](https://github.com/dataloop-ai/components/assets/121247551/3f89fe9d-a5e9-4a1f-bfdc-65489f54930d)

3. **Coloring issue:**
* Do not use variables. 
* Calculate the contrast of text color depending on the background. This means that if I have a light background, the text will automatically be darker and vice versa. The text color is hard-coded. Dark text: #17123, light text:#fff (those are the default values)
* Do not use opacity to color the cells. 
![Screenshot 2023-06-05 at 10 50 10](https://github.com/dataloop-ai/components/assets/121247551/2cad1796-c92f-45c0-bc7c-8351684f9fed)
Use hardcoded colors for both light and dark themes. The colors are on Figma. 

4. Tooltip - The background color is missing.
![Screenshot 2023-06-05 at 10 50 43](https://github.com/dataloop-ai/components/assets/121247551/e0f5da9a-21da-49cc-b80c-19315c40f90e)

5. Labels (axis x only)- To enhance readability, align labels horizontally while using the zoom brush. ![Screenshot 2023-06-05 at 10 49 34](https://github.com/dataloop-ai/components/assets/121247551/7748ad7a-e4ec-47a5-82a5-bdf1b7511f8a)
6. Zoom brush (range selector). - Grabbing the button and dragging it to the desired location is very difficult. It doesn't work smoothly

**Comment by prodan-eric** [comment]
Some of the changes were reconsidered in a discussion with @ rotemshaham around this issue.  I increased the font size and made the labels rotate only when they don't fit horizontally along a cell. We decided on using opacity for the background as that is dynamic and can be used with any color from the props to this component.
