### ISSUE TITLE
[BUG] {{ dl card }} - {{ IU issue }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#386]
At the top-right of the container, the image covers the border.
![Screenshot 2023-06-05 at 11 07 51](https://github.com/dataloop-ai/components/assets/121247551/7a7c5d8b-bd87-4dd7-bee6-965c38321d29)
![Screenshot 2023-06-05 at 11 07 47](https://github.com/dataloop-ai/components/assets/121247551/16440828-3372-4a48-9831-415fe8297e3d)

**Comment by vadim-popa-opentech** [comment]
![image](https://github.com/dataloop-ai/components/assets/127128115/759748fa-a29b-4cf7-9247-48a2ee9cc682)

@rotemshaham according to the latest changes, this issue can't be reproduced
