### ISSUE TITLE
[BUG] {{ dl ellipsis}} - {{ UI issue }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#389]
The ellipses are not displayed in the demo
![Screenshot 2023-06-05 at 11 23 59](https://github.com/dataloop-ai/components/assets/121247551/20d44c52-0fd1-4856-af9e-c137ada68efa)

**Comment by vadim-popa-opentech** [comment]
@rotemshaham according to the latest changes we can't reproduce this issue. 
![image](https://github.com/dataloop-ai/components/assets/127128115/8b383846-44fa-40ff-8718-9c7ddbd5d42a)
