### ISSUE TITLE
[FEATURE] {{ dl thumbnail gallery }} - {{ UI changes }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#391]
1. Change the overlay opacity to 0.3 
![Screenshot 2023-06-05 at 11 43 12](https://github.com/dataloop-ai/components/assets/121247551/c6d45eb3-5ff8-4677-8276-9eaf4fcfccbc)
3. Add border color on hover: dl-color-hover.
4. Change the border to 2px when an image is selected. 
5. The image itself has no corner radius
![Screenshot 2023-06-05 at 11 31 26](https://github.com/dataloop-ai/components/assets/121247551/765bdd63-c687-4391-9cd7-deb55f76d80c)
![Screenshot 2023-06-05 at 11 31 20](https://github.com/dataloop-ai/components/assets/121247551/ba86f585-1adb-4be3-bd10-a07be6b5137a)

**Comment by fadiDL** [comment]
@rotemshaham what is this component ?
