### ISSUE TITLE
[BUG] dl-checkbox - sub label padding

### ISSUE THREAD

**Issue by dlZmiro** [dataloop-ai/components#407]
Hey,
when using sub label slot , the orginal class of sub-text still exists and the left padding cannot be changed.

**To Reproduce**
1- create a dl checkbox
2- add sub label slot and create your own text.
3- original class attributes cannot be changed.

**Expected behavior**
should not display the class at least without padding.

**Screenshots**
![image](https://github.com/dataloop-ai/components/assets/117907222/76a0ec1f-080f-4869-b095-a53a6db92ad1)

**Device**
 - OS: macOS
 - Browser Chrome
 - Version 114.0.5735.106

**Comment by prodan-eric** [comment]
removed the default padding. you can set it now by assigning a value to a CSS variable (--dl-checkbox-sub-label-left-padding)

**Comment by fadiDL** [comment]
Added default value of 20px to the variable as well.
