### ISSUE TITLE
DlCheckBox wrong datatype supplied

### ISSUE THREAD

**Issue by ai-hemant** [dataloop-ai/components#44]
**Describe the bug**

**To Reproduce**
1. Use the table component.
2. Check the checkbox-related feature (selection of the rows)
3. Click on Checkbox and see the following console error.

```
[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Array, Boolean, String, Number, Object, Function, got Null
```

**Expected behavior**
There is a type-related issue that should not have been there.

[src/components/DlTable/DlTable.vue:959](https://github.com/dataloop-ai/components/blob/main/src/components/DlTable/DlTable.vue#L960)
This prop is expecting a boolean value and has been given a null value.

**Comment by fadiDL** [comment]
@SorinOpt was this fixed in the #58 ?
