### ISSUE TITLE
[BUG] {{ DlMenu }} - {{ Jumps when opening another menu }}

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#468]
See video.

https://github.com/dataloop-ai/components/assets/120374103/47308a2c-3f3e-496c-b787-fab95ac75acc

(FYI: Does not happen with DlPopup)

**Comment by fadiDL** [comment]
Root cause was vue2 behavior with portal + transition. 
for now we dont use timeout for the animations anymore.

**Comment by fadiDL** [comment]
Root cause was vue2 behavior with portal + transition.
for now we dont use timeout for the animations anymore.
