### ISSUE TITLE
[BUG] DlInput - wrong padding when action slot exist

### ISSUE THREAD

**Issue by giladDataloop** [dataloop-ai/components#487]
**Describe the bug**
When using the 'action' slot, the padding is pushing the sloted component 'out' of it's place

**Expected behavior**
Should set padding-left to 30px.

**Screenshots**
from prod:
![image](https://github.com/dataloop-ai/components/assets/99115433/773112db-14b2-43cc-bb05-2c9de4450602)
 (input with the title 'IAM User ARN')

**Device (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by fadiDL** [comment]
Seems to work fine components wise. please reopen a jira ticket on the matter for OA handling

**Comment by fadiDL** [comment]
Reopening as it is related to the dl-input component in many ways

following is a list of issues with the component 

1. The component is larger than its container
![image](https://github.com/dataloop-ai/components/assets/99925584/f5fb1044-3334-4a4c-9cd6-6865165cc203)

2. The component does not flex-grow and does not accomidate the actions button 
![image](https://github.com/dataloop-ai/components/assets/99925584/98649731-c29c-4581-ba0e-ae88f5298625)


I tried to refactor the code to support it in a flex form but its too intrecated at the moment. this needs a full rewrite of the component again..
