### ISSUE TITLE
[FEATURE] DL Table - Sticky Columns

### ISSUE THREAD

**Issue by dlZmiro** [dataloop-ai/components#508]
**Problem**:
The "dl table" component doesn't currently support keeping both the first and last columns sticky while scrolling horizontally. This makes it difficult to work with tables having many columns, as one of these columns is always out of view, causing inconvenience in referencing the data.

**Solution**:
I suggest adding a feature that allows both the first and last columns to stay fixed on the screen while scrolling horizontally. This way, users can always see these important columns, making it easier to understand the data.

**Additional context**
![image](https://github.com/dataloop-ai/components/assets/117907222/65cd30c0-7510-4fbb-9a01-35baeb784123)
As you can see, the first and last columns are not visible while scrolling

**Comment by fadiDL** [comment]
This needs further definition
@rotemshaham what kind of sticky columns do we want / need ? what is the behavior ? is the above enough ?
