### ISSUE TITLE
DlGrid > improvements and restructuring 

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#51]
Today we have 2 main components for widget handling with dl-grid and dl-grid-row

We want to merge these two components into one with specific API

```
<dl-grid 
 layout=”[2,3]”
/>
```

Props: 
Layout -> null | array of numbers

If layout is null the grid is a flex style container that just displays grid where it allows multiple items in the container by size and by min size and restructure 

otherwise the format of layout is an array of numbers where the length of the array is the amount of rows and each row contains layout[rowIndex] columns.

**Comment by fadiDL** [comment]
@VictorOpenTech FYI

**Comment by vadim-popa-opentech** [comment]
@VictorOpenTech  this task has been done in https://github.com/dataloop-ai/components/pull/93 PR
