### ISSUE TITLE
[BUG] {{ DlButton/DlDropdownButton }} - {{ icon is using the wrong color }}

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#530]
![image](https://github.com/dataloop-ai/components/assets/120374103/16ca8097-0a07-430f-8463-86cdc91ed5a7)
![image](https://github.com/dataloop-ai/components/assets/120374103/bc7fa2bb-d50f-4e1a-bcdf-7dc3a439ef2c)

Before, when using `color='secondary'` would use 'dl-color-darker' on the text automatically and on hover there would be a tint of blue. The icon on light mode was invisible. We need the icon color to behave the same as the label.

Expected behavior:
When using color="secondary" the text and the icon should use 'dl-color-darker' and have a tint of blue on hover.

**Comment by fadiDL** [comment]
This was triggered by #516 . 
this needs more indepth handling as root cause is affecting every button and dropdown button.
