### ISSUE TITLE
[BUG] dl-select / button - small glitch of styling 

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#532]
**Describe the bug**
1) dl-button icon does not get state of hover
2) dl-select icon is too big (is not follow the icon side small/medium/large) 

![image](https://github.com/dataloop-ai/components/assets/127755482/bb047762-81c3-4d3d-9ef0-28a432e1ca7a)

**Comment by fadiDL** [comment]
Color was fixed
in terms of sizing having a button with an icon does change the icon size according to the size of the button
