### ISSUE TITLE
[BUG] DialogBox - Height of dialog box footer is causing footer to overflow

### ISSUE THREAD

**Issue by ai-hemant** [dataloop-ai/components#533]
**Describe the bug**
The dialog box footer slot is going out of the boundary of the footer because of the height of the footer. The issue can be resolved by:
1. Remove the height property of the footer and instead add max-height (recommended)
2. Define the value of `dl-dialog-box-footer-height` variable.

**To Reproduce**
1. use the dialog box component
4. use the footer slot and add HTML which has a height more than 35px
5. The content would be overflown out of the footer boundary.

checked on components version: `v0.18.8` and higher

**Expected behavior**
The footer HTML should not have been overflown.

**Screenshots**
<img width="1915" alt="Screenshot 2023-08-08 at 12 13 12 PM" src="https://github.com/dataloop-ai/components/assets/125646532/6d78a3ff-d825-44a1-b563-427cd8a7ea2c">

**Device (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 114.0.57

**Comment by fadiDL** [comment]
removed heights of footer and header as they are supposed to be fit-content.
