### ISSUE TITLE
[FEATURE] {{ general empty state for filters }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#555]
Figma: https://www.figma.com/file/UTx83SSFrIOohMzG9e2rAj/dataloop-design-system?type=design&node-id=16862%3A23244&mode=design&t=yBpGLelNb5DKZ7Dt-1

Title: No results were found for the selected filters.
Text: Try to filter different options to find what you’re looking for.

![Screenshot 2023-08-17 at 10 10 38](https://github.com/dataloop-ai/components/assets/121247551/e8ba2b87-b489-49c6-a890-f080e0d71480)

**Comment by fadiDL** [comment]
@rotemshaham this will be implemented on the developer side as the filters are not part of any component here and the table does have a default empty state
