### ISSUE TITLE
DlTable > missing using `pagination.rowsNumber`

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#58]
**Describe the bug**
dl-table does not show the amount of pages in table navigation according to the number in `pagination.rowsNumber` so there is always 1! page. 

**To Reproduce**
1. create `<dl-table :pagination="{rowsNumber :1010, rowsPerPage :100 }">` 
2. render it

**Expected behavior**
in the navigation area should appear 5 pages for immediate click and more 6 pages should appear when scrolling right 
![image](https://user-images.githubusercontent.com/127755482/226328447-ea89909f-9dfa-4c73-9511-7a0a00985d08.png)
and the text `Showing 1-100 of 1010 Rows` 

**Screenshots**
![image](https://user-images.githubusercontent.com/127755482/226328837-a4d84b6e-3f68-412a-a34c-83e69e9d04a9.png)
in the above, we see 63105 but just one (1!) page in table’s navigation

**Comment by SorinOpt** [comment]
Fixed in PR [28](https://github.com/dataloop-ai/components/issues/28)

**Comment by perydataloop** [comment]
I forgot to mention that some sort of request should be triggered for the missing data for the page that the user clicks on
