### ISSUE TITLE
[BUG] DlSmartSearch - allow special characters in text

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#585]
currently we cannot use any special keys like 

(  ) \ / * . 

inside a string '' it gets cleaned out

**Comment by binary3oul** [comment]
@fadiDL  Can you please reproduce this issue?

**Comment by amzgrouplab** [comment]
okay



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/03/23,
10:58:03 AM

**Comment by binary3oul** [comment]
https://github.com/dataloop-ai/components/assets/134395032/ed0a515f-1d03-4fe7-9c40-aa311134c7ea

Please check this video. I can not reproduce this issue on my end.
Could you please share the reproduction?

**Comment by binary3oul** [comment]
?

**Comment by dataitai** [comment]
Please review the bug for further information in the attached video.
https://share.zight.com/NQu5rpgb

**Comment by binary3oul** [comment]
Could you please share the source code of that site in the video?
The code in this repo works well.
