### ISSUE TITLE
[BUG] DlSmartSearch - use suggestion issue with non schema key

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#591]
when the field is not matched in use-suggestions function it doesnt return any basic suggestions even tho next character is space

**Comment by amzgrouplab** [comment]
Hi there!

1. Check the code in the use-suggestions function to see how it processes the input field. Ensure that the code is working as intended and check if there are any places where you may be missing the space.

2. Check the basic suggestions array (if this is being used) to ensure that all the basic suggestions are present and that they are being accessed correctly when the input field is not matched.

3. Create a condition to check if there is a space after the input that is not matching and there are no basic suggestions returned. If this is the case, then return basic suggestions as applicable.

4. Ensure that you test the updated function thoroughly to ensure that the basic suggestions are being returned correctly when there is no match and the next character is space.

I hope this helps you to resolve the issue. If you face any further issues or have any questions, please don't hesitate to ask.

**Comment by binary3oul** [comment]
@fadiDL  I am a freelancer from Upwork.  Can I create PR?

**Comment by amzgrouplab** [comment]
Sure


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/03/23,
09:27:40 AM

**Comment by binary3oul** [comment]
@fadiDL  I am ready for PR, please lmk when you are available.

**Comment by amzgrouplab** [comment]
I am available now.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/03/23,
10:09:04 AM

**Comment by binary3oul** [comment]
What is the expected behavior in the video?
