### ISSUE TITLE
[BUG] DlSmartSearch - cant set caret at correct position when using inputs.

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#592]
When using the smart search today we cannot seem to update the previously written text by replacing the caret at that position and editing. 
This is a result of the way we save the caret on the editable content div that is our search input.

**Comment by amzgrouplab** [comment]
Hi there!

1. First, you need to determine how the caret is being saved on your editable content div. You can check the code to see if there's a way to update or modify the implementation of this feature.

2. Next, you need to check if the selStart and selEnd properties are being updated correctly when users click on or interact with your input field. If not, make sure to update these properties accordingly to correctly place the caret at the desired position.

3. Use JavaScript's string manipulation functions to insert, delete, or replace text at the desired location. Once you have the selStart and selEnd properties, you can use these functions to manipulate the text without disrupting the rest of the content.

4. Listen for input events and update the value of the input field whenever the user enters or modifies any text. This will ensure that the input field reflects the latest value entered by the user.

I hope this helps you to resolve the issue with DlSmartSearch. If you face any further issues or have any questions, please don't hesitate to ask.

Thanks

**Comment by dataitai** [comment]
Please review the bug for further information in the attached video.
https://share.zight.com/8Lu6Pg8O

**Comment by binary3oul** [comment]
Is this job still available? Can I create PR?
