### ISSUE TITLE
[BUG] DlTable - Virtual scroll and empty state dont play well

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#609]
When having rows but passing isEmpty to dl-table 
this ist he result 
![image](https://github.com/dataloop-ai/components/assets/99925584/2db7e1d5-b90d-4fb3-8814-8cb7d2ffb191)

It should only be one time..

**Comment by RotemDl** [comment]
@fadiDL @guyDataloop I'm not able to reproduce and it doesn't seem like dl-table even has an isEmpty prop.
Can this be closed?
