### ISSUE TITLE
[BUG] DlDateTimeRange - When having auto-close and choosing option from select options tit doesn't close

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#630]
When having 
autoclose
multi

props active and clicking on last 7 days for example 
the popup does not close automatically..

**Comment by makc-dataloop** [comment]
cant seem to reproduce:

https://github.com/dataloop-ai/components/assets/146977958/3b8edd7f-4c0a-46e4-aa82-f2d90c6d394a
