### ISSUE TITLE
[BUG] DlLabelPicker - Missing labels children from level 2 and above  

### ISSUE THREAD

**Issue by orshabtay** [dataloop-ai/components#676]
**Describe the bug**
After reaching level 2, the child is not displayed(B-B-B), and not receiving any events on the selectedLabel.

**To Reproduce**
In rc - lidar studio (using the this component)
recipe with more than 2 levels of children for a label.

**Expected behavior**
Should display all levels and get event for each

**Comment by fadiDL** [comment]
@orshabtay there was an issue with the component due to recent changes to the dl-tree-table 
I fixed the issues and updated the demo page so you can see nesting of 4 levels working well.
