### ISSUE TITLE
[FEATURE] DlGrid - Optional Virtual Scroll

### ISSUE THREAD

**Issue by RotemDl** [dataloop-ai/components#702]
**Is your feature request related to a problem? Please describe.**
Recently virtual scroll ability was added to DlGrid. It's much needed, so that's great. One thing that isn't quite working as expected is the conditional virtual scroll. There was an internal condition that when there are less than 100 item to display, virtual scroll will not be activated. That didn't work as expected - when there were less than 100 items, nothing was displayed. The quick solution was to always enable virtual scroll.
For some situations this is overkill and also the scroll still has some issues that can be completely avoided in some cases.

**Describe the solution you'd like**
Allow for a boolean prop to enable virtual-scroll (like we have in the table) and also an item amount threshold only after which the virtual scroll should be activated.

**Comment by SorinOpt** [comment]
![image](https://github.com/dataloop-ai/components/assets/127127362/2b798408-e4f4-4b83-8351-53c224e5cdc6)
@RotemDl  not sure if this should be an && or an ||, let me know

**Comment by RotemDl** [comment]
@SorinOpt should be an &&. The threshold should be a prop as well, not a hardcoded 100
