### ISSUE TITLE
[FEATURE] DlSmartSearch - Value Aliasing

### ISSUE THREAD

**Issue by RotemDl** [dataloop-ai/components#727]
**Is your feature request related to a problem? Please describe.**
Many times when we query resources, they are connected to other resources only by ID. For example, searching for an execution by pipeline ID. For better UX, we would like to allow the user to search by name (which makes sense in cases where the name is unique), for ease of use, yet the actual value that will be sent in the query is the ID.

**Describe the solution you'd like**
Allow aliasing values of specific fields using a dictionary (key is the alias, value is the actual value), and allow the user to input "value" that matches the key aliases. 
Should support auto-suggest, should be strict (because an unknown alias can't be converted)

**Comment by makc-dataloop** [comment]
Progress:

https://github.com/dataloop-ai/components/assets/146977958/8f15f463-5fe0-433d-86a5-64da53350b00
