### ISSUE TITLE
[BUG] {{ DlTable/Pagination }} - {{ When rows-per-page has a single digit selection, the dropdown doesn't show the options }}

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#729]
**Describe the bug**
When selecting a single digit "rows per page" number (for example: 5), and viewing in smaller screens/zooming in - the options in the dropdown are hidden.
Please see video.

https://github.com/dataloop-ai/components/assets/120374103/964921e1-7d1d-4533-a146-07308c261ae0

**Comment by SorinOpt** [comment]
![image](https://github.com/dataloop-ai/components/assets/127127362/1361a8e8-cf3d-416c-9502-538f06f34458)
Cannot reproduce this bug. please provide more context about the implemenetation

**Comment by advaa1234** [comment]
Hey, nothing special about the implementation. Just passing rows-per-page to dl-table. You can check in the platform, go to the pipelines page table like in the video, pick “5”, zoom in, and it should happen.

**Comment by SorinOpt** [comment]
We only have access to the source code of the library itself and the demos we've created. If there's a bug on the platform amd we don't have the context about it, there's no way to debug it. The rows-per-page prop renders the menu well in the cases we have, so unless we can reproduce it on the demo page, we can't address it.
