### ISSUE TITLE
[BUG] {{ SmartSearch }} - {{ Cannot enter search in a range }}

### ISSUE THREAD

**Issue by ShlomiAvigdor** [dataloop-ai/components#768]
Try to fill item input search with filters of a range, greater than some value but smaller than another:
For item search:
- createdAt < 05/12/2023 AND createdAt > 01/12/2023
- metadata.system.size < 10 AND metadata.system.size > 1

For Annotation search:
- confidence > 0.1 AND confidence < 0.9

The component will sanitize the input and wont allow the search

**Comment by fadiDL** [comment]
Closing as #755 is merged
