### ISSUE TITLE
[BUG] DlSmartSearchInput - suggestion does not open

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#770]
When clicking on the sides of the inputs it does not auto trigger the menu to open
but only when clicking the middle it will open the menu

**Comment by makc-dataloop** [comment]
@fadiDL can you please check again? this seems to work fine for me:

https://github.com/dataloop-ai/components/assets/146977958/875700f1-737b-49e8-85fb-554509917fd4

**Comment by fadiDL** [comment]
Closing as not reproduced
