### ISSUE TITLE
[BUG] {{ dl input }} - {{ tooltip is missing when the text is longer than the width container }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#774]
Display a tooltip on hover with the entire name in case of a long label. 
![Screenshot 2023-12-18 at 11 31 07](https://github.com/dataloop-ai/components/assets/121247551/2919ec4b-40a3-449d-bd2e-6fbff727c90e)

**Comment by Anilpandiya** [comment]
@rotemshaham, @fadiDL  I have fixed this bug but I don't have permission to push my branch to remote.

_remote: Permission to dataloop-ai/components.git denied to Anilpandiya._

![chrome_bAcRoNLtWM](https://github.com/dataloop-ai/components/assets/13769938/a411b26e-a324-407f-aa7e-f823b9cebaa8)
