### ISSUE TITLE
[BUG] {{ DL Smart Search }} - {{ last deleted letter is coming back after a deletion  }}

### ISSUE THREAD

**Issue by MatanEden7** [dataloop-ai/components#782]
Video - https://share.zight.com/o0uOoz7l

**Comment by makc-dataloop** [comment]
@guyDataloop Matan confirmed this is not reproducible any more
<img width="663" alt="Screenshot 2024-05-14 at 10 00 28 AM" src="https://github.com/dataloop-ai/components/assets/146977958/236d0ef1-1216-4b0f-980a-bac632ff89f6">
