### ISSUE TITLE
[BUG] {{ Labe picker }} - {{ UI issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#791]
**Search bar:**
1. The search height should be 28px. <img width="473" alt="Screenshot 2023-12-26 at 11 44 08" src="https://github.com/dataloop-ai/components/assets/121247551/ffccd000-d0e7-4b78-b197-f47d94073ba6">
2. The search icon has the wrong color. The correct color is dl-color-lighter. 
<img width="201" alt="Screenshot 2023-12-26 at 11 56 51" src="https://github.com/dataloop-ai/components/assets/121247551/49659fee-7273-4b86-b62a-618a495c50e7">

3. The search icon is jumping while starting to type. 

https://github.com/dataloop-ai/components/assets/121247551/3dd6e0d8-c949-45ab-95e8-1b8b783e96a2

4. Focus mode (the border is not highlighted) is missing.
5. Spacing: The spacing between the search icon to the other elements (placeholder & the search border) should be 10px (left & right).
6. The placeholder should be aligned to the left. For some reason is in the center. Also, the text starts from the center. <img width="231" alt="Screenshot 2023-12-26 at 11 43 37" src="https://github.com/dataloop-ai/components/assets/121247551/098e15f2-0783-4343-a964-3c9fd2ce45c8">
<img width="201" alt="Screenshot 2023-12-26 at 11 43 32" src="https://github.com/dataloop-ai/components/assets/121247551/f0bc23a0-d87e-4702-a0b9-aadcaf6320d7">
7. The placeholder has the wrong text. Please change the text to: Search a label 
<img width="201" alt="Screenshot 2023-12-26 at 11 56 51" src="https://github.com/dataloop-ai/components/assets/121247551/49659fee-7273-4b86-b62a-618a495c50e7">

**Label list**
1. When no sub-labels (no chevrons)- the label should aligned with the search bar with padding-left of 10px. <img width="282" alt="Screenshot 2023-12-26 at 11 57 20" src="https://github.com/dataloop-ai/components/assets/121247551/0e88d292-957a-4230-ab34-7b4cac81f4f0">
2. The label row height should be 32px (for some reason is 40px). <img width="435" alt="Screenshot 2023-12-26 at 11 57 12" src="https://github.com/dataloop-ai/components/assets/121247551/ea93fa34-db3d-43cb-9058-fb6c6249a382">
3. The label color indication is too small. The height should be as the row height (32px).
4. The gap between rows should be 4px. 
5. The gap between the search bar with the first top label should be 10px. 
6. The selected highlighted color is missing when a label is selected.

**Comment by fadiDL** [comment]
@guyDataloop this component is only used in our applications for now. we should let the team work on it specifically for their needs
