### ISSUE TITLE
[FEATURE] DlDateTImeRange - add support for single day/time selection

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#841]
Currently supported:
Day with show-time:
![image](https://github.com/dataloop-ai/components/assets/120374103/78afe5da-69e5-4887-b59f-1c9f17c650bc)

Day without time:
![image](https://github.com/dataloop-ai/components/assets/120374103/1f567e90-6d1b-46ba-8f83-f853dd0ca2ec)

Month:
![image](https://github.com/dataloop-ai/components/assets/120374103/e3b42b38-b871-4420-9c99-841183afa41a)

Need support for single day/time selection:
![image](https://github.com/dataloop-ai/components/assets/120374103/7ce028aa-2cd1-4f10-a1f8-017c8f57970e)

**Comment by fadiDL** [comment]
@makc-dataloop we will have to create a new component called 
DlDateTimePicker 
and implement it for a single date with time range in that day 
The reason is that we do not want to change the DlDateTimeRange as it works on a range by definition.
