### ISSUE TITLE
[BUG] DlSelect - scroller issues

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#866]
No scroller
* OA:
![image](https://github.com/dataloop-ai/components/assets/120374103/31bd8645-d5c3-4a21-9512-150b0afe2346)
* Components:
![image](https://github.com/dataloop-ai/components/assets/120374103/19ece86f-f0ba-41d9-a5e3-03d07c8005ed)

**Comment by makc-dataloop** [comment]
cant reproduce OA part (see JIRA), 2nd part seems to be fine tho? it's just bad data in the demo, I will commit better one, hold on

**Comment by makc-dataloop** [comment]
ah wait, you mean the scroller part... welp:
<img width="1220" alt="Screenshot 2024-02-09 at 11 53 47 AM" src="https://github.com/dataloop-ai/components/assets/146977958/a941f0c3-8dac-4923-871e-6806e3b724fd">

I have a scroller. It seems like there is some way to break it, that you have successfully triggered
