### ISSUE TITLE
[BUG] smart search - 'Created at' and 'Updated at' with '='

### ISSUE THREAD

**Issue by MatanEden11** [dataloop-ai/components#902]
Scenario: 

Open the service page

Click on the smart search 

Search created at or updated at with = 

Actual: No results  (filter a specific time in the day and not the range of the entire day) 

Expected: All the results created at or updated at this date should be displayed (Should filter a range of the entire day)

**Comment by guyDataloop** [comment]
Related ticket and discussion - https://dataloop.atlassian.net/browse/DAT-71033
