### ISSUE TITLE
dl-select: can't select item from the list with `arrow keys` and `enter`

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#92]
**Describe the bug**
when dropdown are open and user can't use arrow keys to naviage up and down and select item with `enter` 

**To Reproduce**
1. Go to [dl-select](https://dataloop-ai.github.io/components/?path=/docs/library-components-dlselect--docs)
2. Click on `dl-select` element, drop down will open
3. push on `arrow-down` key 
4. nothing happen

**Expected behavior**
1) expect that the first item will be highlighted when the `arrow-down` key is clicked, and other item will be highlighted as the user continues to navigate up and down with the `up` and `down` arrow keys. pushing on `enter` will select the highlighted item

2) same think in the `dl-text-input` suggestion popup

**Comment by fadiDL** [comment]
Note this also happens with all of our other portal based menus

**Comment by prodan-eric** [comment]
fixed in the PR for a related issue - https://github.com/dataloop-ai/components/pull/133
